name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          eval "$(ssh-agent -s)"
          ssh-add /home/ubuntu/.ssh/id_rsa
          ssh-add -l  # Verify the key is loaded

      - name: Deploy to EC2 via SSH
        run: |
          scp -r ./* ubuntu@13.53.87.90:/var/www/My-portfolio
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
