name: Deploy to EC2

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      runs-on: ubuntu-latest
      env:
        NODE_VERSION: '20.x'

    - name: Install SSH
      run: sudo apt-get install openssh-client
      
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no \
          -i ${{ secrets.SSH_PRIVATE_KEY }} \
          ubuntu@your-ec2-instance-ip \
          'cd /var/www/maku && git pull origin main && sudo systemctl restart nginx'
