name: Deploy to EC2

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH
      run: sudo apt-get install openssh-client
      
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no \
          -i ${{ secrets.EC2_SSH_KEY }} \
          ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} \
          'cd ${{ secrets.TARGET_DIR }} && git pull origin main && sudo systemctl restart nginx'
